name: Docker Image CI for GHCI

on: 
  push

jobs:
  publish-bandito-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and Push the image (AMD64)
        run: |
          docker login --username rmcmillan34 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --file Dockerfile-amd64 --tag ghcr.io/rmcmillan34/bandito:latest-amd64
          docker push ghcr.io/rmcmillan34/bandito:latest-amd64
 
  publish-bandito-arm64:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push the image (ARM64)
        run: |
          docker login --username rmcmillan34 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --file ./Dockerfile-arm64v8 --tag ghcr.io/rmcmillan34/bandito:latest-arm64v8 --platform linux/arm/v8
          docker push ghcr.io/rmcmillan34/bandito:latest-arm64v8
          
