name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    with:
    registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Bandito Docker image
      run: 
        docker build . --file Dockerfile --tag bandito:$(date +%s)
        docker run ghrc.io/rjmcmillan34/bandito:$(date +%s)
        docker push ghcr.io/rjmcmillan34/bandito:$(date +%s)
