name: Docker Image CI for GHCI

on: 
  push

jobs:
  publish-CTF_hackaton-arm64:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push the image (ARM64)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.MY_PASS }}
        run: |
          docker login --username $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD ghcr.io
          docker build . --file ./Dockerfile --tag ghcr.io/$DOCKER_USERNAME/CTF_hackaton:latest-arm64v8 --platform linux/arm64
          docker push ghcr.io/$DOCKER_USERNAME/CTF_hackaton:latest-arm64v8
